[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
srtree = { path = "../srtree" }
rand = "0.8.5"
criterion = "0.3"
rtree_rs = "0.1.4"
rstar = "0.9.3"
petal-neighbors = "0.8.0"
ndarray = "0.15"

[[bench]]
name = "srtree"
harness = false
